#!/bin/bash

WDIR=$(dirname ${BASH_SOURCE[0]})
MANIFESTS=$WDIR/../../kubernetes/istio/manifests
FILENAME=$WDIR/../../kubernetes/istio/manifests/profiles/demo.yaml

echo $MANIFESTS
echo $FILENAME
# Install isio with istioctl
# istioctl install --manifests $MANIFESTS --filename $FILENAME

istioctl install --set profile=demo --filename $FILENAME